---
- name: Fetch k3s install script
  ansible.builtin.uri:
    url: "{{ k3s_install_url }}"
    return_content: true
  delegate_to: localhost
  run_once: true
  register: _k3s_script

- name: Install k3s cluster
  ansible.builtin.command:
    cmd: sh -
    stdin: "{{ _k3s_script['content'] }}"
  register: _k3s_status
  changed_when: "'No change detected' not in _k3s_status.stdout"
  environment:
   K3S_KUBECONFIG_MODE: "644"
   INSTALL_K3S_EXEC: "--disable=servicelb"

- name: Create kubeconfig directory
  ansible.builtin.file:
    path: /home/vagrant/.kube
    owner: vagrant
    group: vagrant
    mode: 0755
    state: directory

- name: Fetch k3s kubeconfig
  ansible.builtin.slurp:
    path: /etc/rancher/k3s/k3s.yaml
  register: _k3s_kubeconfig

- name: Write k3s kubeconfig
  ansible.builtin.copy:
    content: "{{ _k3s_kubeconfig['content'] | b64decode | to_nice_yaml }}"
    dest: /home/vagrant/.kube/config
    owner: vagrant
    group: vagrant
    mode: '0644'
